### ISSUE TITLE
Support for Hyper-V

### ISSUE THREAD

**Issue by joaocc** [boxcutter/ubuntu#10]
Hi,
What is needed to add support for Hyper-V?
Do I need to change anything other than ```./ubuntu/script/vmtool.sh```?
Thanks

**Comment by annawake** [comment]
I dunno.  If you ever work this out, submit a PR.  Last time I tried using Hyper-V with vagrant, the most challenging aspect was that the vagrant provider did absolutely nothing to configure the network, so it will prompt you asking what virtual switch you want to connect to.  I think that will be the most challenging aspect - documenting how to configure networking as it is not read from the Vagrantfile.

**Comment by dwickern** [comment]
I was able to build a hyper-v box using my [virtualbox-to-hyperv](https://github.com/dwickern/packer-post-processor-virtualbox-to-hyperv) plugin.

You can see the changes I made at dwickern/packer-ubuntu@cec3476d2e743c6052f3c104127ede8783fee4c1 (I've only tested and published ubuntu 14)
