### ISSUE TITLE
Language issues in box-cutter/ubuntu1604-desktop (virtualbox, 2.0.26)

### ISSUE THREAD

**Issue by clavecoder** [boxcutter/ubuntu#101]
Could not start **gnome-terminal** without using `dbus-launch`. Would always get exit code 8. After many askubuntu machinations, paid $50 on guru.com to get the fix. Please add to the box image:

1. sudo apt-get update
1. sudo gnome-language-selector
1. It's going to prompt you about being incomplete, click next and let it download/apply the locale data.
1. Hit 'Apply System Wide' for good measure (probably unnecessary)
1. Reboot

**Comment by clavecoder** [comment]
Looks like someone already has a PR for it: #100

**Comment by dragon788** [comment]
Another quick fix for this is to edit `/etc/default/locale` and correct the two `en_US` references by adding `.UTF-8` (need to edit as root and save and reboot).

**Comment by thisismydesign** [comment]
Any update on this issue?

**Comment by tknerr** [comment]
Can confirm that setting the locale as suggested by @dragon788 fixes the issue.

Had it working by adding `update-locale LANG=en_US.UTF-8` somewhere in `scripts/*.sh`, but the combination of PR #100 (setting the locale to `en_US.UTF-8`) and PR #103 (passing that locale to VirtualBox and Parallels builders too) seems like the proper fix for me.
