### ISSUE TITLE
Ubuntu Desktop 12.04.4 (64-bit) needs to be updated to 12.04.5

### ISSUE THREAD

**Issue by d3netxer** [boxcutter/ubuntu#12]
The old link couldn't download the iso for me with 12.04.4

You can upgrade to 12.04.5 and use the link below.
http://releases.ubuntu.com/12.04/ubuntu-12.04.5-alternate-amd64.iso

**Comment by rasa** [comment]
We tried 12.04.5 but reverted to 12.04.4 in https://github.com/boxcutter/ubuntu/commit/ef35f3d6d7ad37aeee69741d63b1d61fb82580d0

**Comment by d3netxer** [comment]
@rasa Did it not work for 12.04.5? It didn't for me.

Id 12.04.4 still working for you? It is not downloading the ISO anymore for me.

**Comment by d3netxer** [comment]
@rasa oh I see you changed the link in the commit, cool! let-me try it out!

**Comment by d3netxer** [comment]
@rasa After the machine boots up. It get's paused waiting to ssh into it.

**Comment by rasa** [comment]
Reopening at it doesn't seem to have fixed the issue.

**Comment by annawake** [comment]
It's unlikely that the 12.04.5 media will be fixed, and since no one has yet volunteered to investigate a workaround, closing for now.  Addressed in 14.0.x and higher.
