### ISSUE TITLE
new ubuntu builds?

### ISSUE THREAD

**Issue by dominikzogg** [boxcutter/ubuntu#120]
The last update on https://app.vagrantup.com/boxcutter/boxes/ubuntu1604 is about 8 months ago. Did you dropped any support?

**Comment by AlekSi** [comment]
Ping.

**Comment by misheska** [comment]
We no longer provide pre-built binaries, just the templates.

**Comment by greaber** [comment]
What is the rationale for not providing pre-built binaries?  Is there someone else who is doing this?  It seems way more convenient to be able to just do "vagrant init ... && vagrant up" than to have to build these images by hand.

My use case, by the way, is just that I am looking for a reliable and maintained Ubuntu 16.04 Desktop image (for GUI use) for the VirtualBox provider.  Not sure if boxcutter is even the best option for this or not.

**Comment by dominikzogg** [comment]
@greaber i suggest to use bento/ubuntu-16.04
