### ISSUE TITLE
Unable to open terminal in Ubuntu 16.04 desktop 

### ISSUE THREAD

**Issue by endejoli** [boxcutter/ubuntu#121]
I am using below Vagrantfile to bring up a Ubuntu desktop VM in wndows10.  VM comes up fine, but when I click on terminal inside Ubuntu, it does not launch the terminal. 

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box         = "boxcutter/ubuntu1604-desktop"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
       vb.memory = "2048"
       vb.cpus = "2"
    end
    config.vm.provision "file", source: "setup.sh", destination: "setup.sh"
end

**Comment by ddavidebor** [comment]
same

**Comment by mendhak** [comment]
I had this same problem, I see it reported [here](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1578830) but it seems to be a locale problem.

I tried a bunch of commands and rebooted, and that seems to have fixed the problem but I don't know which of these actually fixed it. I ran these in xterm

    sudo locale-gen
    localectl set-keymap US
    localectl set-x11-keymap US
 
Then a `vagrant halt` and `vagrant up`.  Now Ctrl+Alt+T works.

**Comment by ddavidebor** [comment]
yep

**Comment by lqueryvg** [comment]
I had this too. Managed to get it working as above, but still unable to search for the terminal in the Unity dash.

Similar to what's described here.

https://askubuntu.com/questions/113302/cant-search-for-terminal-in-unity-dash

Tried all sorts of suggested solutions but giving up. I've wasted too much time on this already.

**Comment by dragon788** [comment]
There are multiple PRs open to fix this but so far the maintainers haven't merged any of those.

**Comment by lqueryvg** [comment]
https://github.com/boxcutter/ubuntu/issues/121#issuecomment-327268449 didn't fix it for me.

**Comment by dragon788** [comment]
Have you tried the other fix mentioned [here](https://github.com/boxcutter/ubuntu/issues/101#issuecomment-272342501)?

**Comment by lqueryvg** [comment]
Ok, well I did this and it now seems to work...

- cloned this repo at latest commit (fd499fb)
- modified `ubuntu1604-desktop.json` to point at server iso:

      "iso_checksum": "ee834fbeb94cc55972b38caafa2029c29625e2e8",
      "iso_url": "http://releases.ubuntu.com/16.04/ubuntu-16.04.4-server-amd64.iso",

- `packer build -only=virtualbox -var-file=ubuntu1604-desktop.json ubuntu.json`
- `cd box/virtualbox`
- `vagrant init ubuntu1604-desktop ubuntu1604-desktop-0.1.0.box`
- `vagrant up`
- `vagrant ssh`
- `cat /etc/default/locale`

      #  File generated by update-locale
      LANG="en_US.UTF-8"
      LANGUAGE="en_US:"

I'm not sure exactly what combination of circumstances is making it work this time.

**Comment by npmeyer** [comment]
I can also confirm that the terminal issue appears to be fixed (I built the image from [58f500b](https://github.com/boxcutter/ubuntu/commit/58f500b8f2dd9642149a2dcb22bbe7444482cbc2).
