### ISSUE TITLE
Vagrant Cloud chaos with BoxCutter

### ISSUE THREAD

**Issue by Vad1mo** [boxcutter/ubuntu#124]
In Vagrant Cloud  there are two groups:
**boxcutter** and **box-cutter**

https://app.vagrantup.com/boxcutter/
https://app.vagrantup.com/box-xcutter/

This repo refers to **boxcutter** but the images are in **box-cutter**?

this has changed recently as boxcutter doesn't seems to work anymore.

**Comment by dominikzogg** [comment]
@Vad1mo you've got a typo in the link https://app.vagrantup.com/box-xcutter/ => https://app.vagrantup.com/box-cutter/

**Comment by Vad1mo** [comment]
yes sorry it was a typo. however the questions  stays.

**Comment by dominikzogg** [comment]
@Vad1mo i know, use the box with my setup: https://github.com/vagrant-php/ubuntu, fixed the name. But it seems its not supported anymore, as you can see within #120
