### ISSUE TITLE
32 bit templates

### ISSUE THREAD

**Issue by ZubairLK** [boxcutter/ubuntu#131]
Hi,

I was searching for 32-bit ubuntu packer templates and came across a commit to remove them
https://github.com/boxcutter/ubuntu/commit/58f32c0d73ac52cc395d53c07adeca6a9313b9b6

Was there any reason to do this?
Any roadblocks I need to be aware of before proceeding with trying it out.

Also, I'll be looking at ubuntu-desktop versions if that is relevant.

Thanks

Regards,
ZubairLK

**Comment by misheska** [comment]
Nothing was wrong with the 32-bit templates when we removed them. We just wanted to avoid having another platform to build that was rarely used for the pre-built images (when we did that).
