### ISSUE TITLE
403 forbidden on http://cdn.boxcutter.io/

### ISSUE THREAD

**Issue by keyen999** [boxcutter/ubuntu#133]
Accessing http://cdn.boxcutter.io/ seems not possible right now?
Is this #70 re-appearing?

I get a 403 with body like 
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...</RequestId><HostId>...</HostId></Error>
```

Specific URL I wanted to access was 
https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box, which redirected to http://cdn.boxcutter.io/ubuntu/virtualbox5.1.10/ubuntu1604-desktop-2.0.26.box

URL was accessed through "vagrant up" command with configuration 
`config.vm.box = "box-cutter/ubuntu1604-desktop"`

**Comment by miratim** [comment]
I'm seeing this too

**Comment by jamime** [comment]
Same here for `box-cutter/ubuntu1604-desktop`.

**Comment by annawake** [comment]
We no longer provide pre-built vagrant box binaries

**Comment by annawake** [comment]
We no longer provide pre-built vagrant box binaries

**Comment by annawake** [comment]
We no longer provide pre-built vagrant box binaries

**Comment by jamime** [comment]
Thanks @annawake will you be maintaining the packer configs still?

**Comment by justincampbell** [comment]
HashiCorp has received a few support requests regarding 403 errors when attempting to download boxcutter Vagrant boxes. Vagrant Cloud does offer free hosting for publicly available Vagrant boxes. If you would like you can upload the final versions of the boxcutter Vagrant boxes directly to Vagrant Cloud to alleviate the errors users are currently experiencing.

**Comment by avishnyakov** [comment]
Very unfortunate. Broke our internal CI and dev related workflows :)

**Comment by rmhowe** [comment]
@annawake @boxcutter-robot is there any chance of uploading the final versions of the boxes to the Vagrant Cloud free hosting as @justincampbell suggested?

**Comment by misheska** [comment]
Not really. The images go out of date fairly quickly - someone would need to keep up binary builds and verify them against new vagrant versions/desktop virtualization versions. We're no longer doing that. We're just providing templates.
