### ISSUE TITLE
Ubuntu 1604 desktop access denied issue

### ISSUE THREAD

**Issue by satyaki20** [boxcutter/ubuntu#135]
Hi,
When trying to download the ubuntu 1604 ( https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box) getting access denied error 
Response I am getting 
Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>69683B94B5EAE6F5</RequestId>
<HostId>
ESPMhbpHKNnPAv5kIHXOtwhiFqukSY2EFfuQQCBx3fXuAPLtjAPdhzB7M0RHqCRuY1oqom9i2wI=
</HostId>
</Error>
It was available few days back

**Comment by jarofgreen** [comment]
Me to.

It's from http://cdn.boxcutter.io/ubuntu/virtualbox5.0.20/ubuntu1604-desktop-nocm-2.0.18.box and looks like a AWS S3 error.

**Comment by justincampbell** [comment]
See #138

**Comment by misheska** [comment]
We no longer provide pre-built binaries.
