### ISSUE TITLE
How close to a "standard" desktop install?

### ISSUE THREAD

**Issue by PaulWalkerUK** [boxcutter/ubuntu#137]
I've only just started looking at this and am trying to build Ubuntu 16.04 desktop, but I've run into an issue. Before I spend much time trying to fix it, I'd like to get an understanding of what I'm likely to get when it all works 😄 

I gather the desktop build first installs the server version then "adds" desktop on top of it? If that's the case, then how close is the final result to if I did a standard desktop install manually? Is it close enough that it makes no difference, or am I likely to notice?

**Comment by misheska** [comment]
Last time we tried using the ubuntu 16.04 desktop iso, it was impossible to automate the install. We couldn't figure out how to feed in all the necessary preseed values to make the install work automatically. We were getting errors on boot.

The install should be fairly similar to a manual install from the desktop iso, as fundamentally they are the same OS. But I couldn't tell you exactly where they differ, as we haven't done a detailed comparison.

**Comment by dragon788** [comment]
I've used an automated desktop ISO install and this WAY better streamlined alternative quite a lot he. Functionally they are exactly the same, if you want to really get pedantic you can run the regular desktop installer and once you get logged in open a Terminal and run `dpkg --get-selections > regular-desktop.txt` and then set up a VM based off this repo's "desktop" spin and run the command and compare the two files with something like `meld`. One thing you probably won't get by default in an alternative install is the ubuntu-drivers utility and the restricted mp3 codecs et al, but those are also possible to add to this type of preseed install pretty easily.

**Comment by rasa** [comment]
I had this working to install ubuntu_desktop at one time:
````
d-i partman-auto/choose_recipe select atomic
d-i partman-auto/method string        regular
d-i partman/choose_partition select   finish
d-i partman/confirm_nooverwrite boolean true
ubiquity keyboard-configuration/layout select USA
ubiquity keyboard-configuration/layoutcode string us
ubiquity keyboard-configuration/unsupported_layout boolean true
ubiquity ubiquity/reboot boolean true
ubiquity ubiquity/success_command string \
	in-target apt-get -y update ;\
	in-target apt-get install -y openssh-server ;\
	wget -O - "$(sed 's|.*url=\([^ ]*/\).*|\1|' /proc/cmdline)run-http-scripts.sh" | sh -v -s early ;\
	wget -O - "$(sed 's|.*url=\([^ ]*/\).*|\1|' /proc/cmdline)run-http-scripts.sh" | sh -v -s late ;\
	cp /proc/cmdline /target/var/tmp/cmdline.txt ;\
	true
libssl1.0.0       libssl1.0.0/restart-services string
libssl1.0.0       libraries/restart-without-asking boolean true
libssl1.0.0:i386       libssl1.0.0/restart-services string
libssl1.0.0:i386       libraries/restart-without-asking boolean true
libssl1.0.0:amd64       libssl1.0.0/restart-services string
libssl1.0.0:amd64       libraries/restart-without-asking boolean true
d-i partman-auto-lvm/guided_size string max
d-i partman-lvm/confirm_nooverwrite boolean true
d-i pkgsel/upgrade select none
d-i pkgsel/language-pack-patterns string
d-i pkgsel/install-language-support boolean false
d-i pkgsel/language-packs multiselect en
````
