### ISSUE TITLE
Vagrant boxes no longer available on Vagrant Cloud

### ISSUE THREAD

**Issue by cawka** [boxcutter/ubuntu#138]
Is it intentional or something happened?  I have been relying on those boxes for long time now...

**Comment by jarofgreen** [comment]
You will find they have moved to https://app.vagrantup.com/box-cutter - note the hyphen. 

If boxcutter could document that on https://app.vagrantup.com/boxcutter it would really help - thanks!

**Comment by cawka** [comment]
As far as I understand, that was the other way around.  They moved from box-cutter to boxcutter.  Last time boxcutter was working, I got a much more recent version of 16.04 slave (17.0907.1) versus 2.0.26 that was last updated 11 month ago.

**Comment by misheska** [comment]
We no longer provide pre-built binary images
