### ISSUE TITLE
box-cutter/ubuntu1604-desktop cannot be found

### ISSUE THREAD

**Issue by Kiemes** [boxcutter/ubuntu#142]
I cannot use the ubuntu1604-desktop virtualbox image.
Is there anything broken with the URLs, or am I the only one having the issue?

The URL https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box redirects to https://app.vagrantup.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box which redirects to http://cdn.boxcutter.io/ubuntu/virtualbox5.1.10/ubuntu1604-desktop-2.0.26.box

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'box-cutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2.0.26
==> default: Loading metadata for box 'box-cutter/ubuntu1604-desktop'
    default: URL: https://vagrantcloud.com/box-cutter/ubuntu1604-desktop
==> default: Adding box 'box-cutter/ubuntu1604-desktop' (v2.0.26) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

Also opening the URL 'https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box' in the browser brings 

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>smartystreets-boxcutter</BucketName>
<RequestId>15B5F370738E88E0</RequestId>
<HostId>
MW7bvcbe0vojg24GjgD/l7nEoru6VIPwzuukhxUJ/V88B802Gzq5+fQj80L+kQck7m4p3oVgdk0=
</HostId>
</Error>
```

Also it would be appreciated, if all URLs in the chain would be https.

**Comment by misheska** [comment]
We no longer provide pre-built binaries.

**Comment by kristianperkins** [comment]
Are you guys able to update the [vagrant cloud page(s)](https://app.vagrantup.com/box-cutter) do document none of those boxes work anymore?

**Comment by rasa** [comment]
I’m not, sorry. @misheska ?
