### ISSUE TITLE
Ubuntu 16.04.4 Desktop fails to build due update-notifier-common

### ISSUE THREAD

**Issue by myaylaci** [boxcutter/ubuntu#148]
After switching the server image to 16.04.4, the build process bails out, because update-notifier-common is not configured. It is required by update-notifier, which again is required by ubuntu-desktop.

Adding "DEBIAN_FRONTEND=noninteractive" to the provisioners:environment_vars section of ubuntu.json did not change anything (which makes sense, as it's already part of the boot_command)

Yesterday, while beeing on an old version of the repo, I created a build with the 16.04.3 server image. Then I decided to pull the latest boxcutter sources. 

Seems like changes in Ubuntu cause a conflict while updating the previously mentioned packages iteractivly. How to fix that?

**Comment by dragon788** [comment]
If you look at some of the other open issues the problem is probably the desktop ISO being used instead of the server ISO. If you change the download to the server ISO of 16.04.4 and update the checksum it should work.

**Comment by myaylaci** [comment]
Actually, I mentioned it in the first sentence: the server image I am refering to is the server iso. Though, the the server iso itself is not the problem.

I figured out what spoiled the build: the latest ubuntu1604-desktop.json uses preseed-desktop.cfg instead of preseed.cfg. 

After switching back to preseed.cfg I am able to build.
