### ISSUE TITLE
Are there any plans to add ubuntu 18.04?

### ISSUE THREAD

**Issue by mtbvang** [boxcutter/ubuntu#149]
I'm in need of it and will likely try to do it this weekend. I'm just wondering if I'm repeating what some else is already working on?

**Comment by gtrafimenkov** [comment]
Support for Ubuntu 18.04 has already been added.  You can build box using command:

```
packer build -only=virtualbox-iso -var-file=ubuntu1804.json ubuntu.json
```

If you don't want to build the box yourself, you can use this one: https://app.vagrantup.com/devops-toolkit/boxes/ubuntu1804

**Comment by mtbvang** [comment]
Sorry, I meant the 1804 desktop.

**Comment by tknerr** [comment]
@mtbvang see #162 for ubuntu 18.04 desktop support
