### ISSUE TITLE
vagrant cloud images missing

### ISSUE THREAD

**Issue by paleozogt** [boxcutter/ubuntu#150]
I can't create any of the [box-cutter](https://app.vagrantup.com/box-cutter) vagrant images.  For example:

```
➜  vagrant init box-cutter/ubuntu1604-desktop
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

➜  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'box-cutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'box-cutter/ubuntu1604-desktop'
    default: URL: https://vagrantcloud.com/box-cutter/ubuntu1604-desktop
==> default: Adding box 'box-cutter/ubuntu1604-desktop' (v2.0.26) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

**Comment by paleozogt** [comment]
Did you delete them from vagrantcloud?  If so, you should really remove the webpages as they're very misleading now.

**Comment by dusek** [comment]
Since it might be interesting to people reading this issue, I would like to point to an [issue #1573245 in Ubuntu Launchpad for the cloud-images project](https://bugs.launchpad.net/cloud-images/+bug/1573245) where I am requesting Canonical to provide also Ubuntu Desktop images on Vagrant Cloud, in addition to their [Ubuntu Server images](https://app.vagrantup.com/ubuntu) which are already one of the most popular on Vagrant Cloud.

Of course the more support and upvotes (more specifically "This affects me" button) is voiced in that issue, the more chance they will once provide Ubuntu Desktop images as well.

**Comment by BuhtigithuB** [comment]
The point of using boxcutter to me is to generate your own box... If you want a generic base box you can just use the ubuntu already existing on Atlas (vagrant cloud as it seems now).

Someone wanting desktop image can just install/provision the right UI desktop in his vagrantfile... "sudo apt -y install ubuntu-gnome-desktop" over an ubuntu server base box will provide you mostly what ubuntu desktop image variant is...

Don't forget to add this to your vagrantfile in order for the UI to come up : 

config.vm.provider "virtualbox" do |v|
  v.gui = true
end

**Comment by BuhtigithuB** [comment]
I would close this one... As it related to vagrant more then packer, not something related to boxcutter code base...

We might delete this before closing it : 
https://app.vagrantup.com/box-cutter/boxes/ubuntu1604-desktop

**Comment by BuhtigithuB** [comment]
And many more https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=box-cutter

maybe...

:)

**Comment by paleozogt** [comment]
@ BuhtigithuB The problem isn't so much that botcutter doesn't make vagrant boxen, but that they're listed on vagrant cloud and are broken.
