### ISSUE TITLE
Prevent OS from upgrading

### ISSUE THREAD

**Issue by stmichael** [boxcutter/ubuntu#16]
Ubuntu 12.04 asks us if we'd like to upgrade to 14.04 some time after booting. This is a problem for us because the chef run will always fail.

Apparently while the upgrade dialog is open, apt is locked. Our cookbooks try to install packages which fails due to the lock.
```
==> default: STDERR: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> default: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

Could you prevent Ubuntu from asking? A solution for this problem can be found at http://askubuntu.com/questions/115913/disable-ubuntu-update-managers-new-version-warning.

**Comment by annawake** [comment]
Done

**Comment by stmichael** [comment]
Thanks for the quick fix. Do you plan on releasing this fix anytime soon?
