### ISSUE TITLE
Files in  folder cannot be dragged when on Grid View

### ISSUE THREAD

**Issue by FaiScofield** [boxcutter/ubuntu#170]
System: ubuntu 18.04
Problem: Files in  folder cannot be dragged when on Grid View, but it's normal when on List View, why? and how to solve it?

This is Grid View.  Files cannot be dragged to another place in this mode
![grid](https://user-images.githubusercontent.com/18671620/56146740-56c7fe00-5fd9-11e9-94db-db03b4c5687a.jpg)
This is List View. Files can be dragged in this mode.
![list](https://user-images.githubusercontent.com/18671620/56146749-5def0c00-5fd9-11e9-98f1-39a7ac65565b.jpg)

This is an irritated trouble, I which someone can help me to solve it, THANKS!

**Comment by jerryfromearth** [comment]
Try disabling the “experiment view” in Nautilus (the file explorer) preferences.

**Comment by FaiScofield** [comment]
> Try disabling the “experiment view” in Nautilus (the file explorer) preferences.

It works. Thank you~
