### ISSUE TITLE
Selinux enforcing mode Error

### ISSUE THREAD

**Issue by bobbybhaskar** [boxcutter/ubuntu#188]
When I installed the Selinux in Ubuntu 14.04 server and In vi /etc/SELinux/config I changing into SELINUX=permissive  to SELINUX=enforcing mode then rebooting my Ubuntu 14.04 server,  where I am not able to login into the server, it showing error  "/bin/bash permission denied".

OS : Ubuntu 14.04

**Comment by misheska** [comment]
We don't support a SELINUX=enforcing config (and ubuntu 14.04 is now EOL)
