### ISSUE TITLE
Why desktop templates use server images?

### ISSUE THREAD

**Issue by joudaon** [boxcutter/ubuntu#191]
The files:
- ubuntu1404-desktop.json
- ubuntu1604-desktop.json
- ubuntu1804-desktop.json

are using `"iso_url": "http://old-releases.ubuntu.com/releases/bionic/ubuntu-18.04.1-server-amd64.iso",` Why don´t you use desktop image?

**Comment by rickard-von-essen** [comment]
Because the desktop images boot into a desktop and they can't be automated. The desktop install is equivalent of a standard server install plus the `ubuntu-desktop` meta-package.

**Comment by joudaon** [comment]
ooh okay, so it is installed on the `script/desktop.sh` script right? Thank you.

**Comment by rickard-von-essen** [comment]
Yes
