### ISSUE TITLE
Incorrect version of VBox Guest Additions being installed

### ISSUE THREAD

**Issue by dnataraj** [boxcutter/ubuntu#20]
Hi -

I just created a Ubuntu 15.04 box (make virtualbox/ubuntu1504) and afterwards checking the guest additions versions :
```
GuestAdditions versions on your host (5.0.0) and guest (4.3.22_Ubuntu r98236) do not match.
```
the vagrant-vbguest plugin claims in can fix this on vagrant up, but for some reason it does not work on certain kinds of images :

```
Installing Virtualbox Guest Additions 5.0.0 - guest version is 4.3.22_Ubuntu r98236
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.0 Guest Additions for Linux............
VirtualBox Guest Additions installer
You appear to have a version of the VBoxGuestAdditions software
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 5.0.0. Some functionality may not work as intended.
```

Any advice? Thanks.

**Comment by annawake** [comment]
These templates use whatever version is on the machine that you created the box.  Make sure the machine on which you create the vagrant basebox has the version of VirtualBox you want to use (if it is not feasible to upgrade your ubuntu).  The vagrant-vbguest plugin indeed is not very good at downgrading.  But it is relatively easy to create a box with the right guest additions using these templates.
