### ISSUE TITLE
ubuntu1510 does not build

### ISSUE THREAD

**Issue by rrva** [boxcutter/ubuntu#22]
ubuntu1510 does not build, presumably due to changes in the installer. I managed to get past the language selection by changing

```
       "boot_command": [
-        "<esc><esc><enter><wait>",
+        "<enter><esc><enter><wait>",
```

But more is needed. When the boot commands are entered, the installer gets stuck again on language selection. Perhaps a boot commandline option to set the language is needed?

**Comment by jgoldschrafe** [comment]
Investigating the same problem, I noticed it flashed something on the screen really quickly (a single frame) before returning to the language selection screen. I captured the video output in VirtualBox and it just says the following:

    Loading bootlogo...
    
    Initializing gfx code...

Almost entirely worthless, but hopefully this saves someone the time of having to step through the video frame by frame.

**Comment by rrva** [comment]
@jgoldschrafe: check out https://github.com/rrva/dockerhost or https://atlas.hashicorp.com/rrva/boxes/dockerhost if you do not want to build from source

**Comment by andrewsomething** [comment]
FYI: I'm running into the same thing and opened a bug against the installer in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1505839

**Comment by andrewsomething** [comment]
This is pretty ugly, but I've managed to work around this for now by doing:

```
"<enter><wait><f6><esc><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
```

**Comment by ichilton** [comment]
I can confirm that @andrewsomething's workaround worked fine for me :)

**Comment by devekko** [comment]
am new to packer, apologies

how is the workaround used?

I tried placing the "<enter><wait>f6>esc><bs>..... " block in the ubuntu.json file, but it looks like I hit a text limit for the expert mode in the installer and cuts of commands

**Comment by rickard-von-essen** [comment]
See https://github.com/chef/bento/pull/483/files for a working example.

**Comment by annawake** [comment]
It builds now https://github.com/boxcutter/ubuntu/commit/f01883469354db1e7ed92b9b96741b4d29d1b988 - published out to atlas as well.

**Comment by devekko** [comment]
thanks

no vmware provider?
