### ISSUE TITLE
Parallels support

### ISSUE THREAD

**Issue by mblaschke** [boxcutter/ubuntu#27]
Why was Parallels support removed from repository?
It's one of the best virtualization solutions for OSX and cheaper than VMware :)

**Comment by annawake** [comment]
The licensing changes in Parallels 11 make it difficult for us to continue to provide Parallels boxes for free.  The new licensing policy is decidedly anti-automation.  The biggest issue is that the licenses are locked to a single node, and you must call Parallels to move licenses around (even though it says "unlimited" on the maximum licenses allowed in the product comparison matrix).  We have a farm of build nodes which we wipe and restore with the various configurations, as say, Parallels 10 and Parallels 11 cannot exist on the same box.  Now we'd have to pay for a license on each build node, even though we are only building Parallels boxes on one node at a time in the farm.  After contacting Parallels twice about this licensing issue and still having issues with licensing popups, we don't want to deal with this hassle and are waiting for this licensing policy to change.

Also, the change in requiring a Pro or Business license to use vagrant (or any prlctl command) and not being clear about this in the feature matrix is definitely not cool.  There were tons of people contacting us asking why our boxes didn't work with the desktop edition.

**Comment by joliver** [comment]
How many nodes are we talking about? My organization is already sponsoring hosting of the Vagrant boxes and we may be open to paying for the Parallels licenses as well.

**Comment by stephenreay** [comment]
It seems a little odd to just strip out all support, rather than simply not building those targets on your farm for now.

**Comment by joliver** [comment]
@annawake Any thoughts on this? We'd love to provide for the licensing costs if that would help.

**Comment by tehnorm** [comment]
We would also be willing to chip in for license costs if that helps with the popups. 

@intelfx @legal90 @ligurio @racktear would any of you know who best to speak with in the Parallels about bulk or build farm licensing options? Boxcutter does some really solid stuff and it's disappointing to see the removal of a Parallels base box from the community build chain over a popup.

**Comment by racktear** [comment]
Hi,

I'm from Parallels.
We are discussing internally what we can do to help with this. Stay tuned.

@tehnorm thanks for pinging me.

**Comment by tehnorm** [comment]
Hi @racktear thank you for reaching back out so quickly. Excited to see what your discussion yields! Just to be clear I am not affiliated with boxcutter - simply a user of their awesome boxes - parallels primarily. I don't know for certain but believe @annawake and @misheska are part of boxcutter - at least according to the github people tab for boxcutter.

**Comment by iamthechad** [comment]
Is there any way to continue using the older versions of boxes that do support Parallels while we wait for a resolution? I tried grabbing version 1.0.16 of `ubuntu1404-desktop`, and I just get a 403 Forbidden error now.

**Comment by racktear** [comment]
@annawake 

I heard that you have resolved the problems with licensing.
Is there anything else I can help with to move this forward?

**Comment by annawake** [comment]
Addressed by https://github.com/boxcutter/ubuntu/commit/452dfaa758e00bb9b63509f791032783ded980ae and https://github.com/boxcutter/ubuntu/commit/15f416616d7eeb292a32e8c42b6bee65c72c612e
