### ISSUE TITLE
custom_script var not used

### ISSUE THREAD

**Issue by dusek** [boxcutter/ubuntu#30]
I want to build my own customized version of the ubuntu desktop box. I found a very promising `custom_script` var in all .json files, but it is not used anywhere (not elsewhere in the json file, not passed as an environment variable to a script). The sole other place it is used is in the `Makefile`, to translate the `CUSTOM_SCRIPT` environment variable to the value of `custom_script` var if `packer` is run through this `Makefile`.

I think it would be very handy to allow users to supply path to their custom script that allows them to run "one more thing" during the setup of the box (e.g. install additional packages) before the box gets "cleaned up" by further scripts.

Currently, my only way is to patch the .json file to add a new script, or modify an existing script (e.g. `desktop.sh`).

**Comment by dusek** [comment]
Accidentally I found that support for `custom_script` was intentionally (with a reason) removed here: https://github.com/boxcutter/ubuntu/commit/3937773369223a8bac54843849f91380b39df4e6

**Comment by annawake** [comment]
Addressed by https://github.com/boxcutter/ubuntu/commit/d397ed85f0e342a1538fd68015321b6681c73c38
