### ISSUE TITLE
the url in ubuntu1204-desktop.json for the ubuntu12.04 iso isn't valid anymore

### ISSUE THREAD

**Issue by legleux** [boxcutter/ubuntu#32]
The ubuntu release has been updated to 12.04.5. 

When I changed this value to point to the correct iso. The build process doesn't complete and I can't really figure out why.
I think I've narrowed it down to the line in preseed-desktop.cfg file of
d-i pkgsel/include string openssh-server ntp curl
specifically the ntp package. If that is removed it completes. I guess this is a separate issue though.

**Comment by annawake** [comment]
Thanks for the workaround.  Seems to work.

https://github.com/boxcutter/ubuntu/commit/ddf514a253e13b09d86e739e29eb8fc497f60207
