### ISSUE TITLE
Vriable install_vagrant_key: '' expected type 'string'

### ISSUE THREAD

**Issue by alyan2008** [boxcutter/ubuntu#35]
Hi

I have tried to build the VM with packer. I used this command - `make virtualbox/ubuntu1404` and then I have got the error - variable install_vagrant_key: '' expected type 'string'. In ubuntu1404.json I found out that currently we have - ` install_vagrant_key: true`. So, we should changed it, because of the new version of packer v.0.8.6 doesn't support it. Could you please fix it?

**Comment by annawake** [comment]
I believe you are working from an old version of the source code - that make command has not been supported for quite some time (and the issue with the type has also been fixed long ago).

Refresh your source and take a look at the `README.md` for the correct build syntax.
