### ISSUE TITLE
Vagrant box - docker-compose not working 

### ISSUE THREAD

**Issue by hvram1** [boxcutter/ubuntu#37]
I use the following command

     packer  build  -only=virtualbox-iso -var-file=ubuntu1504-docker.json ubuntu.json

My custom-script is

     #!/bin/bash
     apt-get -y update
     apt-get -y install curl wget
     apt-get install -y --force-yes python-pip libyaml-dev libpython2.7-dev
     pip install docker-compose

I see that as part of the purge (minimize.sh ) there are development packages being purged . So I commented out the lines removing build-essential, git and the python boxes

But when I start the box and type docker-compose I get an error saying 
     pkg_resources.DistributionNotFound: six<2,>=1.3.0

 . I have to reinstall python=pip and then install docker-compose and the error goes away 

How do I prevent the removal of the packages during minimize to prevent this ?

**Comment by hvram1** [comment]
I also have removed the orphan and the line that removes the *devel packages . But things are still not working

**Comment by dragon788** [comment]
@hvram1 I don't know that there is an option to prevent the package removal, but you could try just skipping the minimize script by removing it from the template and see if you still run into issues.

**Comment by StefanScherer** [comment]
@hvram1 You might try to install `docker-compose` as it is described in the github releases: https://github.com/docker/compose/releases/tag/1.5.2

```
curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

The Docker team has compiled a binary and so you don't need pip and other things.

**Comment by dragon788** [comment]
Oh yeah, Stefan's comment just reminded me that we had some issues with pip
installing compose where you have to pass the -U  to pip install otherwise
it doesn't upgrade the other necessary components within pip to allow
docker compose to work.

    pip install -U docker-compose

Let me know if that works for you.

**Comment by hvram1** [comment]
The pip part never worked . Finally I went with what @StefanScherer suggested and that seems to work beautifully
