### ISSUE TITLE
ATLAS_USERNAME vs BOX_CUTTER_ATLAS_USERNAME

### ISSUE THREAD

**Issue by bountin** [boxcutter/ubuntu#38]
We're using this repository's packer templates to build some customized boxes. Is there a reason why each box is registered twice with atlas with different environment variables/users?

Also I haven't found the uploading feature of ```make deliver``` which is specified in the readme. It calls ```bin/register_atlas.sh``` but there is just a reference to cdb.boxcutter.io with no upload feature at all (neither Atlas, nor S3 or Artifactory).

Last but not least: Great project :+1:

**Comment by annawake** [comment]
Thanks, it's simply because our sponsors want the boxes delivered to both the box-cuttter and boxcutter accounts, so fair enough.

Nope, we were not able to make the uploading feature public.
