### ISSUE TITLE
This overriding of the user's version variable from their varfile here is kind of dirty

### ISSUE THREAD

**Issue by dragon788** [boxcutter/ubuntu#46]
Found this code when I was unexpectedly kept getting an invalid version even when I hardcoded it. This seems dirty to not make more obvious if people are using the bin/box convenience methods.

```
# main
args "$@"

version=$(cat VERSION)
packer build ${only} -var-file=${var_file} -var "version=${version}" ${packer_template}
```

**Comment by annawake** [comment]
It was never intended that a user could specify a `version`.  That is reserved for the build system.  None of the base templates set `version`.

The only manipulation of version expected is via the `VERSION` file.
