### ISSUE TITLE
403 Forbidden From Atlas for v2.0.14

### ISSUE THREAD

**Issue by Tanzy** [boxcutter/ubuntu#47]
Getting the following when trying to download the box

```
default: Loading metadata for box 'boxcutter/ubuntu1404'
    default: URL: https://atlas.hashicorp.com/boxcutter/ubuntu1404
==> default: Adding box 'boxcutter/ubuntu1404' (v2.0.14) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1404/versions/2.0.14/providers/vmware_desktop.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden
```

**Comment by philgs** [comment]
As a work-around, you can use `vagrant box add --box-version 2.0.13 boxcutter/ubuntu1404` to download the prior version. Use `config.vm.box_version` and `config.vm.box_check_update` to tweak Vagrant's actions to suit.

Yes, even the atlas says the box file for VMware is unavailable. :thumbsdown:

**Comment by StefanScherer** [comment]
Any plans to bring back vmware_desktop box support?
It seems that boxcutter/ubuntu1510 also is missing for VMware.

**Comment by annawake** [comment]
Ubuntu 15.10 is now EOL
