### ISSUE TITLE
v2.0.15 VMware Fusion Pro 8.1.0 hangs: Waiting for HGFS kernel module to load...

### ISSUE THREAD

**Issue by StefanScherer** [boxcutter/ubuntu#48]
I've seen that there are VMware boxes again with v2.0.15. But spinning up the boxcutter/ubuntu hangs using VMware Fusion Pro 8.1.0, Vagrant 1.8.1 at the HGFS kernel module.

```
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'boxcutter/ubuntu1404' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'boxcutter/ubuntu1404'
    default: URL: https://atlas.hashicorp.com/boxcutter/ubuntu1404
==> default: Adding box 'boxcutter/ubuntu1404' (v2.0.15) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1404/versions/2.0.15/providers/vmware_desktop.box
==> default: Successfully added box 'boxcutter/ubuntu1404' (v2.0.15) for 'vmware_desktop'!
==> default: Cloning VMware VM: 'boxcutter/ubuntu1404'. This can take some time...
==> default: Checking if box 'boxcutter/ubuntu1404' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.254.134:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Setting hostname...
==> default: Configuring network adapters within the VM...
==> default: Waiting for HGFS kernel module to load...
```

A `vagrant ssh` works so I had a look inside the VM 

```bash
vagrant@java-ide:/var/log$ grep AUTO_KMODS_ENA /etc/vmware-tools/locations 
answer AUTO_KMODS_ENABLED_ANSWER no
answer AUTO_KMODS_ENABLED no
```

This blog post https://dantehranian.wordpress.com/2014/08/19/vagrant-vmware-resolving-waiting-for-hgfs-kernel-module-timeouts/  mentions that we have to add

```bash
echo "answer AUTO_KMODS_ENABLED yes" | sudo tee -a /etc/vmware-tools/locations
```

But this doesn't seem to work. Plenty of work(around) was done here https://www.vagrantup.com/docs/vmware/kernel-upgrade.html and here https://github.com/mitchellh/vagrant/issues/4362

This is really a pain point using VMware with Vagrant.
Any ideas?

**Comment by goldie80** [comment]
This issue is affecting me too - I've attempted grabbing the latest VMWare Tools and trying those, unfortunately the result is exactly the same :-(

**Comment by StefanScherer** [comment]
I found this one: https://github.com/mitchellh/vagrant/issues/6775 
It seems that the fusion plugin should no longer check for HGFS in newer guest OSes.

**Comment by dragon788** [comment]
If using the latest VMware Tools (10.x from Fusion 8.x and higher) they are using Fuse for HGFS instead of the HGFS kernel module. This definitely confuses Vagrant.

**Comment by taylorotwell** [comment]
I'm having major problems with this on Ubuntu 16.04

**Comment by StefanScherer** [comment]
Mitchell is working on a patch, see mitchellh/vagrant#6775 Let's see if it only will work with open-vm-tools.

**Comment by barkingfoodog** [comment]
@StefanScherer thank you for alerting us about the work on a patch!

**Comment by StefanScherer** [comment]
So this commit shows how to do it https://github.com/cbednarski/packer-ubuntu/compare/7545187b79a2784318470f8aae5495bf0fa46...c0c27378935db8d27aa337c799b50d448c61261e, right?

**Comment by StefanScherer** [comment]
I've just tested the VMware Vagrant plugin 4.0.9 and the boxcutter/ubuntu1404 box v2.0.17 already works, so no change needed in this repo. Tested both on OSX and Windows 7.

**Comment by StefanScherer** [comment]
Hm, but boxcutter/ubuntu1604 times out

```
$ vagrant init boxcutter/ubuntu1604
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
~/code/ubuntu
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'boxcutter/ubuntu1604' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'boxcutter/ubuntu1604'
    default: URL: https://atlas.hashicorp.com/boxcutter/ubuntu1604
==> default: Adding box 'boxcutter/ubuntu1604' (v2.0.17) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1604/versions/2.0.17/providers/vmware_desktop.box
==> default: Successfully added box 'boxcutter/ubuntu1604' (v2.0.17) for 'vmware_desktop'!
==> default: Cloning VMware VM: 'boxcutter/ubuntu1604'. This can take some time...
==> default: Checking if box 'boxcutter/ubuntu1604' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by boztek** [comment]
FWIW I was having this problem but 1604 is working after switching to the following versions:

    > vagrant version
    Installed Version: 1.8.1

    > vagrant plugin list
    vagrant-vmware-fusion (4.0.9)

    > vagrant box list
    boxcutter/ubuntu1604   (vmware_desktop, 2.0.18)

**Comment by StefanScherer** [comment]
@boztek Thanks for sharing. So the 2.0.18 box works still using VMware tools? I'm still learning more details.

**Comment by boztek** [comment]
Haven't looked into details myself - just found a combo that works for me until vagrant 1.8.4 lands which seems to have a fix in the queue.

**Comment by ELLIOTTCABLE** [comment]
I'm still seeing this; but I'm on `vagrant-vmware-fusion (4.0.8)`; and I can't get it to upgrade to `4.0.9`, so perhaps that's it? @boztek, where'd you find `4.0.9`?

    > vagrant plugin update vagrant-vmware-fusion
    Updating plugins: vagrant-vmware-fusion. This may take a few minutes...
    All plugins are up to date.

[Here's the full error](https://gist.github.com/ELLIOTTCABLE/a7fddae94b299ed4c44a064a90f41704), ending with:

    The HGFS kernel module was not found on the running virtual machine.
    This must be installed for shared folders to work properly. Please
    install the VMware tools within the guest and try again. Note that
    the VMware tools installation will succeed even if HGFS fails
    to properly install. Carefully read the output of the VMware tools
    installation to verify the HGFS kernel modules were installed properly.

**Comment by khromov** [comment]
@ELLIOTTCABLE 

Can you try: 

```
vagrant plugin uninstall vagrant-vmware-fusion
vagrant plugin install vagrant-vmware-fusion
```

You should then get the latest version (4.0.10 as of writing this post)
