### ISSUE TITLE
Missing Ubuntu 15.10 Docker

### ISSUE THREAD

**Issue by Zenexer** [boxcutter/ubuntu#49]
Is there any reason 15.10 wouldn't work with Docker?  Docker is the only provider without a lot of shared filesystem caveats, so it'd be useful to have a box for that.  Is this something that just hasn't been attempted, or should I not bother trying because there's some blocking bug?

**Comment by hvram1** [comment]
Try 
```
packer  build  -only=virtualbox-iso  -var "docker=true" ubuntu1510.json 
```

**Comment by annawake** [comment]
Ubuntu 15.10 is now EOL. Though in general, it doesn't make sense to continue doing VM images for Docker given Docker for Mac/Docker for Windows, as I'm not sure there is really a need anymore.
