### ISSUE TITLE
linux-headers* packages are not deleted, but files are missing

### ISSUE THREAD

**Issue by legal90** [boxcutter/ubuntu#5]
The commit https://github.com/boxcutter/ubuntu/commit/bd95a1dacaca57f0c870449d42e88502a30b8ebd suggests that `linux-headers*` packages will not be deleted, but this line in the *cleanup.sh* removes all headers anyway:
```bash
echo "==> Removing anything in /usr/src"
rm -rf /usr/src/*
```
https://github.com/boxcutter/ubuntu/blob/bd95a1dacaca57f0c870449d42e88502a30b8ebd/script/minimize.sh#L47

It means that packages are still marked as installed, but files are missing:
```
$ sudo apt-get update
$ sudo apt-get install debsums
$ debsums linux-headers-3.13.0-32
...
debsums: missing file /usr/src/linux-headers-3.13.0-32-generic/scripts/selinux/genheaders/genheaders (from linux-headers-3.13.0-32-generic package)
debsums: missing file /usr/src/linux-headers-3.13.0-32-generic/scripts/selinux/mdp/.mdp.cmd (from linux-headers-3.13.0-32-generic package)
debsums: missing file /usr/src/linux-headers-3.13.0-32-generic/scripts/selinux/mdp/mdp (from linux-headers-3.13.0-32-generic package)
debsums: missing file /usr/src/linux-headers-3.13.0-32-generic/scripts/sortextable (from linux-headers-3.13.0-32-generic package)
```
 
So, it causes a failure of Parallels Tools update: https://github.com/Parallels/vagrant-parallels/issues/175#issuecomment-77026733 . Parallels Tools installer/updater checks that `linux-header*` packages are installed and expects that appropriate files are available in */usr/src/*
It is really major issue and makes "boxcutter" boxes unusable with the Parallels provider.

**Ways to fix it:**
1) Just revert the commit https://github.com/boxcutter/ubuntu/commit/bd95a1dacaca57f0c870449d42e88502a30b8ebd, so these packages will be removed gracefully on the cleanup step. I don't know about VirtualBox and VMware, but these packages will be installed automatically during the Parallels Tools update. 
Actually, these packages are deleted in boxes from the popular "bento" project and everything is OK there:
https://github.com/chef/bento/blob/ed086b9685aa62541c15476237992a96e5a2a0f4/packer/scripts/ubuntu/cleanup.sh#L4

2) Either do not remove files from `/usr/src` to keep packages consistent.

**Comment by annawake** [comment]
Thanks for the thoughtful analysis - address by https://github.com/boxcutter/ubuntu/commit/350486f081e75cefee12e58c0780f2a7e058265b
