### ISSUE TITLE
Ubuntu docker images java process hang

### ISSUE THREAD

**Issue by rawlink** [boxcutter/ubuntu#57]
There is a known bug in ubuntu and debian kernels that causes java processes in docker containers to zombie and consume 100% CPU. The bug can be found at https://github.com/docker/docker/issues/18180 and the solutions can be found in the comment at https://github.com/docker/docker/issues/18180#issuecomment-193708192. 

I am currently using the boxcutter/ubuntu1404-docker v2.0.16 image. Inside of the image, I updated my linux kernel to linux-image-4.2.0-35 and docker to docker-engine 1.11.0-0 (I actually just ran an 'apt-get update' and an 'apt-get dist-upgrade').

This seems to have resolved the problem with hanging java processes in my docker containers running under the boxcutter/ubuntu1404-docker image. Could you update your images to include the necessary fixes?

Thanks!

**Comment by annawake** [comment]
Given Docker for Mac/Docker for Windows and how time consuming it is to maintain even the non-Docker VMs, we're going to defer to Docker themselves to maintain base images that are patched up so that Docker can run as part of this toolchain.
