### ISSUE TITLE
Minimal ubunt-desktop installation

### ISSUE THREAD

**Issue by jpadilla** [boxcutter/ubuntu#6]
Tried changing the `desktop.sh` to instead use `apt-get install -y --no-install-recommends ubuntu-desktop` which I saw commented in favor for the full install. Any reasons for the decision? I gave it a try but desktop never actually launches. It'd be ideal not having to have all those open office apps installed by default.

**Comment by annawake** [comment]
I believe you see the reason from the results ;-)  If you figure out the issue, we accept PRs ;-) ;-)

**Comment by jpadilla** [comment]
Closest thing for now is running purge on this [list](https://gist.github.com/jimbocoder/14f76f27b96685d7a29a). But there's still a lot of things that could probably be optimized on that desktop environment to make it more snappy.

**Comment by jpadilla** [comment]
This might also be interesting to try later http://askubuntu.com/a/42977
