### ISSUE TITLE
ubuntu1604/vmware_fusion - Startup timesout

### ISSUE THREAD

**Issue by yogendra** [boxcutter/ubuntu#60]
I was trying to start a vm with ubuntu1604 box. I don't have anything else in Vagrantfile, except config.vm.box  line. When I start vm using vagrant up, I gets stuck on "Waiting for machine to boot." message for a while, and then just throws an error stating increase timeout. 

After a bit of trial and error with following command, I found that in the interfaces file, `ens33` interface is configured instead of `ens32`.

```shell 
VAGRANT_INFO=info vagrant up
....
....

 INFO vmware_driver: Reading VMX data...
 INFO vmware_driver: Reading DHCP lease for '00:0c:29:2f:98:43' on 'vmnet8'
 INFO vmware_driver: DHCP leases file: [#<Pathname:/var/db/vmware/vmnet-dhcpd-vmnet8.leases>, #<Pathname:/var/db/vmware/vmnet-dhcpd-vmnet8.leases~>]
 INFO dhcp_lease_file: Initialized DHCP helper: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
 INFO dhcp_lease_file: Looking for IP for MAC: 00:0c:29:2f:98:43
 INFO dhcp_lease_file:   - IP:
 INFO dhcp_lease_file: Initialized DHCP helper: /var/db/vmware/vmnet-dhcpd-vmnet8.leases~
 INFO dhcp_lease_file: Looking for IP for MAC: 00:0c:29:2f:98:43
 INFO dhcp_lease_file:   - IP:
....

```

I manually updated file `/etc/network/interfaces` and change `ens33` to `ens32`. 
Then I brought up interface using `sudo ifup ens32`

So, question is how to make this change permanent? Of is my VMware messed up?

**Comment by rickard-von-essen** [comment]
See https://github.com/chef/bento/issues/554 and related PR.

**Comment by hmahmood** [comment]
Any updates on this?

**Comment by cbednarski** [comment]
Hey folks, I hacked around this inside the OS: https://github.com/cbednarski/packer-ubuntu/blob/master/scripts-1604/vm_cleanup.sh#L9-L15

There seems to be some idiosyncrasy between packer, vagrant, and the guest OS version. I'm not really sure if there's a way to magically fix this without some OS-specific switching in Vagrant or Packer, so for now I've worked around it in the provisioning process.
