### ISSUE TITLE
Switch to open-vm-tools?

### ISSUE THREAD

**Issue by StefanScherer** [boxcutter/ubuntu#66]
I followed the discussion in mitchellh/vagrant#6775 and #48 it seems to be better to switch from VMware Tools to the open-vm-tools.

The boxcutter/ubuntu1404 v2.0.17 works fine with Vmware Fusion plugin 4.0.9, Vagrant 1.8.1 and Fusion Pro 8.1.
But with boxcutter/ubuntu1604 v2.0.17 Vagrant hangs connecting to the box. Don't know if that is related with which tools are used.

**Comment by annawake** [comment]
We have switched to using open-vm-tools
