### ISSUE TITLE
Feature: Ubuntu16.04-- Support the Libvirt Provider

### ISSUE THREAD

**Issue by ericpulvino** [boxcutter/ubuntu#67]
I love the boxcutter images. I use them for all my examples and deployments. To support libvirt I have been mutating the boxes to support the libvirt provider however this is not the ideal solution, since Hashicorp allows for storage of the libvirt provider images it would be great if you can start packing images for that provider and provide a trusted authoritative source for libvirt images.

Mutating images for new providers is not fully sufficient any longer due to issues like this ( https://github.com/vagrant-libvirt/vagrant-libvirt/issues/607 ) it would be ideal to have an image that was natively packed for libvirt.

**Comment by annawake** [comment]
Please submit a PR with an implementation and we would be more than willing to consider including it.
