### ISSUE TITLE
CDN Down

### ISSUE THREAD

**Issue by rlweb** [boxcutter/ubuntu#70]
I'm getting the following when trying to access boxcutters/ubuntu image. I'm wondering if you're aware of the issue?

This is when I try and access:
https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1604/versions/2.0.18/providers/vmware_desktop.box
it redirects to:
http://cdn.boxcutter.io/ubuntu/vmware10.0.5/ubuntu1604-nocm-2.0.18.box

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D523D642297393AF</RequestId>
<HostId>
B03AIhl/FT2tN6AK2fpS+j9KKbYyTq4w/ofSJJnufvSdkbOdmW74YmZ1J5Gsrter0rFeuFQUzGY=
</HostId>
</Error>
```

**Comment by StefanScherer** [comment]
It seems that the VMware boxes aren't available yet. Atlas also shows a warning sign https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1604

**Comment by annawake** [comment]
Fine now.
