### ISSUE TITLE
ubuntu16.04 LTS automatic sleep will narrow the right window.

### ISSUE THREAD

**Issue by chenyangguang** [boxcutter/ubuntu#71]
My system info like Linux v 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux.
If  i leave it alone until it comes to the suspend mode. later,  The whole window will narrow about 1/9 every time if i continue to enter my password to login. Everytime... the reduce window become black with nothing on the right side.

**Comment by annawake** [comment]
Insufficient information to reasonably troublehsooot
