### ISSUE TITLE
Patch VMWare Tools

### ISSUE THREAD

**Issue by mathewpeterson** [boxcutter/ubuntu#8]
Can we patch the vmware tools like was was done in boxcutter/debian#8? 

You can read more about the issue in boxcutter/debian#7

**Comment by rasa** [comment]
I can tackle this. @misheska: sound like a good plan? This puts a dependency on having internet connectivity. Is this acceptable?

**Comment by mikeputnam** [comment]
:+1: Bump

**Comment by mathewpeterson** [comment]
Is there anything I can do to help get this in? 

I would argue that creating an image already has a dependency on having internet access.

**Comment by rasa** [comment]
I will get to this, but it won't be for a few weeks, as I'm travelling. If someone else is willing, you just need to mimic the work done in https://github.com/boxcutter/debian/pull/8.

**Comment by harrisony** [comment]
I've submitted pull request https://github.com/boxcutter/ubuntu/pull/11 to resolve this :smiley:

**Comment by rasa** [comment]
Fixed by #11.
