### ISSUE TITLE
Unable to boot 1604 64-bit server on VMware Fusion w/vmxnet3

### ISSUE THREAD

**Issue by josdotso** [boxcutter/ubuntu#81]
Adding this line [1] to this Vagrantfile [2], the machine hangs at [3].

1: `v.vmx["ethernet0.virtualDev"] = "vmxnet3"`

2: https://vagrantcloud.com/boxcutter/boxes/ubuntu1604/versions/2.0.23

3: `==> default: Waiting for machine to boot. This may take a few minutes...`

Is this expected behavior?

Edit 1: Fixed item number 3.  Pasted the wrong line on first pass.

**Comment by annawake** [comment]
Does this work on other VMware Fusion boxes with vagrant?

**Comment by misheska** [comment]
Likely an issue with an older verson of vagrant. Closed due to age.
