### ISSUE TITLE
Build 'virtualbox-iso' errored: Error removing floppy controller

### ISSUE THREAD

**Issue by cplerch** [boxcutter/ubuntu#89]
On Windows 7 x64, When I execute:

`packer build -only=virtualbox-iso -var-file=ubuntu1604.json ubuntu.json`

 I get this error after cleanup.sh successfully terminates:

`==> virtualbox-iso: Gracefully halting virtual machine...`
`        virtualbox-iso: Removing floppy drive...`
`==> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine 'ubuntu1604' is already locked for a session (or being unlocked)`
`==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown`
`==> virtualbox-iso: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp`
`==> virtualbox-iso: Unregistering and deleting virtual machine...`
`==> virtualbox-iso: Deleting output directory...`
...
`==> Builds finished but no artifacts were created.`

Is this something related to packer, to VBoxManage or to how your scripts are using these utils?
VBox version = 5.1.10 (latest)

**Comment by rickard-von-essen** [comment]
Which version of Packer do you have? There has been a fix for this in (at
least) the latest version.

**Comment by cplerch** [comment]
`>packer -version`
0.12.0

`>vboxmanage -version`
5.1.10r112026

**Comment by rickard-von-essen** [comment]
Try to adjust [post_shutdown_delay](https://www.packer.io/docs/builders/virtualbox-iso.html#post_shutdown_delay)

**Comment by cplerch** [comment]
Will try. Can you please give me a short hint where exactly to put this parameter

**Comment by rickard-von-essen** [comment]
```json
      "output_directory": "output-{{ user `vm_name` }}-virtualbox-iso",
      "shutdown_command": "echo '{{ user `ssh_password` }}'|sudo -S shutdown -P now",
      "post_shutdown_delay": "5m",
      "ssh_password": "{{ user `ssh_password` }}",
      "ssh_username": "{{ user `ssh_username` }}",
      "ssh_wait_timeout": "10000s",
      "type": "virtualbox-iso",
```

**Comment by cplerch** [comment]
Thank you very much!
It worked now with just a 1m delay.

**Comment by annawake** [comment]
https://github.com/boxcutter/ubuntu/commit/05ff63e51ec51ba3521d181318dc91a33e27f528
