### ISSUE TITLE
update=true grows the box from 409Mb to 630Mb

### ISSUE THREAD

**Issue by nedbat** [boxcutter/ubuntu#91]
I made an Ubuntu 16.04.1 box: it was 409Mb.  Then I tried setting "update":"true", and the resulting box was 630Mb.  That seems like a very large difference for just updating the packages that are already installed.  Does this seem right?  Is there something more that can be cleaned up to bring the size back down?

**Comment by nedbat** [comment]
I did some more investigating, and a large part of the difference is having two kernels (the original and the updated):
/boot is 53Mb in the original, 101Mb updated.
/usr/src is 120Mb vs. 240Mb.

The usual advice seems to be to keep an old kernel around in case you need it.  But with update=false, we only have one kernel version, so how bad would it be to only have one after update=true?

**Comment by nedbat** [comment]
This seems like a good way to get rid of all but the most recent kernel:
```
sudo purge-old-kernels --keep 1
```
Though it doesn't get all of the /usr/src bits.

**Comment by nedbat** [comment]
There's still a bit of a difference in box sizes (about 30-50Mb), but I don't understand why.  Maybe this is as good as it gets :)

**Comment by tknerr** [comment]
👍 for fixing the removal of old kernel packages

Relatedly: PR #104 which updates to the most recent 16.04.2 iso image
