### ISSUE TITLE
Vagrant - Boxes. htpps pb - Download

### ISSUE THREAD

**Issue by RicoRay** [boxcutter/ubuntu#97]
Hi, 

Using vagrant, I'm unable to update /download any of your boxes. 
It seems to have a certificat problem.
For example, the redirection on this url rises an "access denied" : http://cdn.boxcutter.io/ubuntu/virtualbox5.1.10/ubuntu1610-desktop-2.0.26.box

Regards

**Comment by annawake** [comment]
Not seeing this issue - reopen if it is still a problem.
